import { NextRequest, NextResponse } from 'next/server';
import { requireAnyRole } from '@/lib/auth';

export const POST = async (request: NextRequest) => {
  try {
    console.log('PDF export - parsing request body...');
    const body = await request.json();
    console.log('PDF export - parsed body:', body);
    const { range = 'week', generatedAt = new Date().toISOString() } = body;
    
    // For now, use mock data to ensure PDF export works
    // TODO: Replace with real database data once database connection is stable
    const plannerResult = {
      assignments: [
        {
          screeningId: 'screening-1',
          userId: 'user-1',
          role: 'TECHNIEK',
        },
        {
          screeningId: 'screening-1',
          userId: 'user-2',
          role: 'ZAALWACHT',
        },
      ],
      deficits: [
        {
          screeningId: 'screening-2',
          role: 'TECHNIEK',
          needed: 2,
          available: 1,
        },
      ],
      screenings: [
        {
          id: 'screening-1',
          filmTitle: 'Hetty\'s adventure',
          startsAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
          location: 'Main Theater',
          assignments: [
            { userId: 'user-1', userName: 'Alice Johnson', role: 'TECHNIEK' },
            { userId: 'user-2', userName: 'Bob Smith', role: 'ZAALWACHT' },
          ],
        },
        {
          id: 'screening-2',
          filmTitle: 'Andre Rieu\'s 2025 Christmas Concert',
          startsAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
          location: 'Main Theater',
          assignments: [
            { userId: 'user-3', userName: 'Carol Davis', role: 'TECHNIEK' },
          ],
        },
      ],
    };

    // For now, we'll create a simple HTML version that can be printed to PDF
    // In a production environment, you'd want to use a proper PDF library like puppeteer or jsPDF
    
    const htmlContent = `<!DOCTYPE html>
<html>
<head>
  <title>Film Theater Planning - ${range === 'week' ? 'Next Week' : 'Next Month'}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 20px; }
    .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #333; padding-bottom: 10px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
    th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
    th { background-color: #f2f2f2; font-weight: bold; }
  </style>
</head>
<body>
  <div class="header">
    <h1>Film Theater Planning</h1>
    <h2>${range === 'week' ? 'Next Week' : 'Next Month'} Schedule</h2>
    <p>Generated on ${new Date(generatedAt).toLocaleString()}</p>
  </div>

  <h3>Assignment Overview</h3>
  <table>
    <thead>
      <tr>
        <th>Movie</th>
        <th>Start Time</th>
        <th>Location</th>
        <th>Assignments</th>
      </tr>
    </thead>
    <tbody>
      ${plannerResult.screenings.map(screening => `
        <tr>
          <td><strong>${screening.filmTitle}</strong></td>
          <td>${new Date(screening.startsAt).toLocaleString()}</td>
          <td>${screening.location}</td>
          <td>${screening.assignments.map(a => `${a.userName} (${a.role})`).join(', ')}</td>
        </tr>
      `).join('')}
    </tbody>
  </table>

  <div class="footer">
    <p>This planning was generated by the Film Theater Planning System</p>
  </div>
</body>
</html>`;

    return new NextResponse(htmlContent, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `attachment; filename="planning-${range}-${new Date().toISOString().split('T')[0]}.html"`,
      },
    });
  } catch (error) {
    console.error('Error generating PDF export:', error);
    console.error('Error details:', {
      message: error instanceof Error ? error.message : 'Unknown error',
      stack: error instanceof Error ? error.stack : undefined,
    });
    return NextResponse.json(
      { 
        success: false, 
        error: 'Failed to generate PDF export',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
};


